### ISSUE TITLE
Is it possible to provide a Sklearn wrapper for this code?

### ISSUE THREAD

**Issue by zhenlingcn** [brendenpetersen/deep-symbolic-regression#5]
This work is unprecedented in the symbolic regression domain, and I think it can work as a good benchmark in machine learning and the symbolic regression domain. Although the code is well written and easy to understand, I feel that providing a Sklearn wrapper will further let other people use this method easier in their own code. Therefore, is it possible to provide a Sklearn wrapper for this code?

**Comment by brendenpetersen** [comment]
Hi @zhenlingcn, this is an excellent idea that will make the code much easier to use in existing workflows, as you suggest. Currently the code is set up to run more in batch setting, e.g. to launch large, parallelized runs with multiple independent replicates and possibly multiple datasets. I will add this to the short list for features.

By the way, please look out for a new release in the coming weeks! We have lots of new features and improvements that we haven't yet included in our public release.

**Comment by brendenpetersen** [comment]
Hi again @zhenlingcn , thank you again very much for your suggestion and your PR. Today we updated the codebase to follow our ICLR release. It now contains an sklearn-like interface via the `DeepSymbolicRegressor` object. Please see the README for how to use it!
