### ISSUE TITLE
Is it possible to provide a Tensorflow 2 compatible version of this code?

### ISSUE THREAD

**Issue by zhenlingcn** [brendenpetersen/deep-symbolic-regression#6]
This code is a very good example of using the deep learning technique on the symbolic regression problem. However, up to now, the most up to date deep learning algorithms are implemented in Pytorch and Tensorflow 2. So, is it possible to provide a Tensorflow 2 compatible version of this code? By the way, I know that I can directly enable TensorFlow 2 to run TensorFlow 1 code by disabling all TensorFlow 2 features. Nonetheless, this function does not support the "contrib" package of Tensorflow 1, which is widely used in this project.

**Comment by brendenpetersen** [comment]
Hi, thank you for your interest! We may be able to migrate to TF2, but unfortunately it's not a very high priority for as we focus on new features and research methods. We would be happy to accept a PR that adds compatibility for both TF1/2.
