### ISSUE TITLE
How to check the searched formula?

### ISSUE THREAD

**Issue by pone7** [brendenpetersen/deep-symbolic-regression#8]
Thanks for your contribution to symbolic regression! I am very interested in your work. I ran the code and found that there are only various indicators in the .csv log file, not the formulas searched during the training process. Is there an easier way to view it?

**Comment by brendenpetersen** [comment]
Hey, thanks for your interest! The code currently saves only the final expression at the end of each training run. If you do a simple run with `python -m dsr.run config.json` it will save each run summary as a single line in `benchmark_dsr.csv`. The column "traversal" will show you the best found expression. The logs like `dsr_Nguyen-1_0.csv` show batch statistics each training step.

In a recent update, we've added two additional logging features: 1) saving the "hall of fame" (top `N` expressions found during all of training) and 2) saving the Pareto front (based on a complexity measure). Would this be what you're looking for?

Also please note we will push a new release version shortly, which will include these features.

**Comment by brendenpetersen** [comment]
Also, if you're in using the instantiated expression (e.g. as an executable function), this came up in #5 and support for this will also be added shortly.

**Comment by brendenpetersen** [comment]
Hi @pone7 , the requested feature has been added. You can now specify a "hall of fame" and/or Pareto front. If using the sklearn interface, you can also interact with the best expression via `DeepSymbolicRegressor.program_`.
